version: '3.8'

services:
  mysql:
      image: mysql:latest
      container_name: mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: user_tracker
      ports:
        - "3306:3306"
      volumes:
        - mysql:/var/lib/mysql
        - ./init.sh:/docker-entrypoint-initdb.d/init.sh
        #- ./init.sql:/script/init.sql
      # command: "--init-file /script/init.sql"
      healthcheck:
        test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
        #test: "mysql user_tracker -u root -p root -e 'SELECT 1;'"
        interval: 10s
        retries: 5
        start_period: 30s
        timeout: 10s

  user-command-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile.command
    container_name: user-command-service
    environment:
      DATABASE_URL: root:root@tcp(mysql:3306)/user_tracker
    ports:
      - "3001:3001"
    depends_on:
      mysql:
        condition: service_healthy

  user-query-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile.query
    container_name: user-query-service
    environment:
      DATABASE_URL: root:root@tcp(mysql:3306)/user_tracker
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy


  task-command-service:
    build:
      context: ./task-service
      dockerfile: Dockerfile.command
    container_name: task-command-service
    environment:
      DATABASE_URL: root:root@tcp(mysql:3306)/task_tracker
    ports:
      - "3002:3002"
    depends_on:
      mysql:
        condition: service_healthy

  task-query-service:
    build:
      context: ./task-service
      dockerfile: Dockerfile.query
    container_name: task-query-service
    environment:
      DATABASE_URL: root:root@tcp(mysql:3306)/task_tracker
    ports:
      - "3003:3003"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql:

